
export default function About() {
    return (
      <div className="about">
        <div className="story">
          <h3>OUR STORY</h3>
          <article title="Text generated by KellyGPT">
            <p>
            In the vibrant heart of the city lies Little Lemon, a charming restaurant born from the dreams of a young chef who brought her family's culinary secrets to the urban landscape. Here, traditional recipes meet modern flair, with each dish crafted from generations-old techniques and locally sourced ingredients. More than just a place to eat, Little Lemon offers a cozy, welcoming atmosphere where every meal is a celebration of family heritage, blending small-town warmth with big city sophistication.
            </p>
          </article>
        </div>
      </div>
    )
  };