import { Link } from "react-router-dom";

export default function Article() {
  return (
    <div className="article">
      <img src={require('../../images/main.jpeg')} alt='Menu'/>
      <div className="article-content">
        <h2>Little Lemon</h2>
        <h3>Chicago</h3>
        <p title="Text generated by KellyGPT">
          Little Lemon is a charming restaurant located in the heart of downtown.<br />
          The menu features a mix of classic and contemporary dishes made with fresh, locally-sourced ingredients.<br />
          It doesn't matter what the occasion might be, <br />
          Little Lemon will beat your expectations.
        </p>
        <Link to="/book" rel="href" aria-label="Go to book a table page">Book a Table</Link>
      </div>
    </div>
  )
};